name = "Elden Ring"

[identifiers]
steam_app_id = 1245620

[[tools]]
name = "Mod Engine 2"
description = "Framework de injeção de código e carregamento de mods para Elden Ring"
winetricks = ["vcrun2022"]
download_url = "https://github.com/soulsmods/ModEngine2/releases/latest"
executable_path = "modengine2.exe"

[[tools]]
name = "Elden Mod Loader"
description = "Carregador de mods (.dll) simples para Elden Ring"
winetricks = ["vcrun2022"]
download_url = "https://github.com/techiew/EldenRingModLoader/releases/latest"
executable_path = "dinput8.dll"
